---
services:
  freqtrade_bbands:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_bbands
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8080"
    command: >
      webserver
      --config /freqtrade/user_data/configs/config-ahmed.json

  freqtrade_andy:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_andy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8084:8080"
    command: >
      webserver
      --config /freqtrade/user_data/configs/config-andy.json