---
services:
  freqtrade_bbands:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_bbands
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-bbands.sqlite
      --config /freqtrade/user_data/configs/config-bbands.json
      --strategy bbands

  freqtrade_kama:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_kama
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-kama.sqlite
      --config /freqtrade/user_data/configs/config-kama.json
      --strategy kama

  freqtrade_psar:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_psar
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-psar.sqlite
      --config /freqtrade/user_data/configs/config-psar.json
      --strategy psar